spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prueba?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


server:
  port: 8081

jwt:
  secretKey: ${JWT_SECRET_KEY}

aws:
  accessKey: ${ACCESS_KEY}
  secretKey: ${SECRET_KEY}
  region: ${REGION}
  bucket-name: ${BUCKET_NAME}
  topic-arn: ${TOPIC_ARN}
